-- CRIANDO TABELA CATEGORIA
CREATE TABLE CATEGORIA (
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DESCRICAO VARCHAR(40) DEFAULT NULL,
  ESTATUS ENUM('A','I') DEFAULT NULL
) ;

-- CRIANDO TABELA PERFIL
CREATE TABLE PERFIL (
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DESCRICAO VARCHAR(40) DEFAULT NULL
) ;

-- INSERINDO DADOS INICIAIS NA TABELA PERFIL
INSERT INTO PERFIL (ID, DESCRICAO) VALUES
(0, 'ADMINISTRADOR'),
(0, 'GERENTE'),
(0, 'OPERADOR');

-- CRIANDO TABELA USUARIO
CREATE TABLE USUARIO (
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(255) DEFAULT NULL,
  USUARIO VARCHAR(60) DEFAULT NULL,
  SENHA VARCHAR(100) DEFAULT NULL,
  PERFIL INT(11) DEFAULT NULL,
  EMAIL VARCHAR(80) DEFAULT NULL,
  IMAGEM VARCHAR(100) DEFAULT NULL,
  ATIVO ENUM('0','1') DEFAULT NULL
) ;

-- CRIANDO TABELA PRODUTOS
CREATE TABLE PRODUTO (
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODIGO VARCHAR(6) DEFAULT NULL,
  DATACADASTRO DATETIME DEFAULT NULL,
  NOME VARCHAR(40) DEFAULT NULL,
  DESCRICAO VARCHAR(255) DEFAULT NULL,
  QUANTIDADE INT(11) DEFAULT NULL,
  COR VARCHAR(40) DEFAULT NULL,
  PRECO DOUBLE DEFAULT NULL,
  DESCONTO DOUBLE DEFAULT NULL,
  IMAGEM VARCHAR(100) DEFAULT NULL,
  CATEGORIA INT(11) DEFAULT NULL,
  ESTATUS ENUM('A','I') DEFAULT NULL,
  PRECODECUSTO DECIMAL(10,2) DEFAULT NULL
);
-- ATERANDO A COLUNA CODIGO DA  TABELA PRODUTO
ALTER TABLE PRODUTO  ADD UNIQUE KEY CODIGO (CODIGO);



CREATE TABLE CLIENTES(
   ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NOME VARCHAR(250) NOT NULL,
   CPF  VARCHAR(20) NOT NULL,
   DATANASCIMENTO DATETIME,
   EMAIL VARCHAR(250)  NOT NULL,
   SENHA  VARCHAR(120)  NOT NULL,
   CEP VARCHAR(20) NOT NULL,
   LOGRADOURO VARCHAR(250) NOT NULL,
   NUMERO VARCHAR(10),
   BAIRRO VARCHAR(250) NOT NULL,
   UF VARCHAR(10),
   CIDADE VARCHAR(250) NOT NULL,
   IMAGEM VARCHAR(120),
   DATACADASTRO DATETIME,
   ATIVO  ENUM('1','0')      
);

-- CRIANDO TABELA VENDA
CREATE TABLE VENDA (
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  DATAVENDA DATETIME DEFAULT NULL,
  VALOR DECIMAL(10,2) DEFAULT NULL,
  STATUS VARCHAR(20),
  CLIENTE INT(11) DEFAULT NULL,
  FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(ID) 
) ;

-- CRIANDO TABELA ITENS VENDA
CREATE TABLE ITENSVENDA (
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  VENDA INT(11) DEFAULT NULL,
  PRODUTO INT(11) DEFAULT NULL,
  QUANTIDADE INT(11) DEFAULT NULL,
  PRECOUNITARIO DOUBLE DEFAULT NULL,
  FOREIGN KEY (VENDA) REFERENCES VENDA(ID),
  FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(ID)
) ;

CREATE TABLE CAIXA(
   ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   USUARIO INT(11), 
   DATAABERTURA DATETIME, 
   DATAFECHAMENTO DATETIME, 
   SALDOINICIAL DECIMAL(10,2), 
   SALDOFINAL DECIMAL(10,2), 
   STATUS VARCHAR(60),
   FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID)
);
CREATE TABLE MOVIMENTACAO(
   ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   TOTALCAIXA DECIMAL(10,2),
   CAIXA INT(11), 
   USUARIO INT(11),
   FOREIGN KEY (CAIXA) REFERENCES CAIXA(ID),
   FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE CONFIGURACOES(
   ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
   RAZAOSOCIAL VARCHAR(200), 
   NOMEFANTASIA VARCHAR(200), 
   CNPJ VARCHAR(20), 
   IE VARCHAR(20),
   IM VARCHAR(20),
   REGIMETRIBUTARIO VARCHAR(100),
   LOGO VARCHAR(100),
   CEP VARCHAR(20) NOT NULL,
   LOGRADOURO VARCHAR(250) NOT NULL,
   NUMERO VARCHAR(10),
   BAIRRO VARCHAR(250) NOT NULL,
   UF VARCHAR(10),
   CIDADE VARCHAR(250) NOT NULL,
   CONTATO VARCHAR(20)
);
CREATE TABLE ESTOQUE(
  ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUTO INT(11),
  QUANTIDADE INT(6),
  ESTOQUEMINIMO INT(6),
  DATACADASTRO DATETIME,
  FOREIGN KEY (PRODUTO) REFERENCES PRODUTO(ID)
);
-- ALTERAÇÕES 
ALTER TABLE USUARIO ADD COLUMN DATACADASTRO DATETIME AFTER IMAGEM;
ALTER TABLE PRODUTO DROP COLUMN QUANTIDADE;

ALTER TABLE VENDA ADD COLUMN USUARIO INT;
ALTER TABLE VENDA ADD FOREIGN KEY (USUARIO) REFERENCES USUARIO(ID);

-- criando tabela formapagamento
CREATE TABLE FORMAPAGAMENTO(
ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
DESCRICAO VARCHAR(100)
);
INSERT INTO FORMAPAGAMENTO VALUES(0,'DINHEIRO'),(0,'DEBITO'),(0,'CREDITO'),(0,'PIX'),(0,'CREDIARIO');

ALTER TABLE VENDA ADD COLUMN CLIENTE INT;
ALTER TABLE VENDA ADD FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(ID);

ALTER TABLE VENDA ADD COLUMN PAGAMENTO INT AFTER STATUS;
ALTER TABLE VENDA ADD FOREIGN KEY (PAGAMENTO) REFERENCES FORMAPAGAMENTO(ID);